# Generated by Django 4.1.7 on 2023-03-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhnya', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=0, default='100', max_digits=5),
        ),
    ]
