# Generated by Django 4.1.7 on 2023-03-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhnya', '0007_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=0, default='', max_digits=5),
        ),
    ]
