# Generated by Django 4.1.7 on 2023-03-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
